server:
  error:
    include-message: always
    path: "/error"

externalProviders:
  config:
    path: "classpath:/externalProviders.yml"

spring:
  mvc:
    log-request-details: false
  security:
    user:
      name: disabled
      password: disabled

oidcng:
  checkToken:
    endpoint_url: "http://localhost:8080/oidc/introspect"
    clientId: "oidcng.localhost.surfconext.nl"
    secret: "secret"

checkToken:
  cache: true
# Feature toggle for searching for linked GrouperGroups and ExternalGroups
support:
  linkedGrouperExternalGroups: true

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/internal"
  endpoint:
    info:
      enabled: true
    mappings:
      enabled: false
  info:
    git:
      mode: full

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
